FROM golang:alpine AS building

RUN apk update && apk add git make
RUN git clone https://github.com/fatedier/frp.git /building
WORKDIR /building

RUN make frps

FROM alpine:latest

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]