FROM golang:latest AS building

RUN apk update && apk add git
RUN git clone https://github.com/fatedier/frp.git building
WORKDIR /building

RUN make frpc

FROM alpine:latest

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]